name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker:
    name: Docker container image
    runs-on: ubuntu-latest

    steps:
    - name: docker login
      uses: actions/checkout@v3
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build Docker image
      run: docker build . --file Dockerfile --tag ridacap/flask-image:$(date +%s)
     
 

   

