name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: docker login
      env:
        DOCKER_USER: ${{ secret.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secret.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ridacap/flask-image:$(date +%s)
      
    - name: Docker Push
      run: docker push ${{secrets.DOCKER_USER}}/RIDACAP/FLASK-IMAGE
        
